server:
  session-timeout: 1800
debug: true
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#dubbo config
dubbo:
  registry:
    address: zookeeper://localhost:2181